# Multiclass SVM 구현

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

#IRIS 데이터 로드
iris =  sns.load_dataset('iris') 
X= iris.iloc[:,:4] #학습할데이터
y = iris.iloc[:,-1] #타겟
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [2]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [3]:
def standardization(train, test):
    scaler = StandardScaler()
    train = scaler.fit_transform(train)
    test = scaler.transform(test)
    return train, test

X_train, X_test = standardization(X_train, X_test)

In [4]:
X_train

array([[ 0.78522493,  0.32015325,  0.77221097,  1.04726529],
       [-0.26563371, -1.29989934,  0.0982814 , -0.11996537],
       [ 0.43493872,  0.78302542,  0.94069336,  1.43634218],
       [-0.84944407,  0.78302542, -1.24957775, -1.28719604],
       [-0.38239578, -1.7627715 ,  0.15444219,  0.13941922],
       [ 0.55170079, -0.374155  ,  1.05301496,  0.7878807 ],
       [ 0.31817664, -0.14271892,  0.65988937,  0.7878807 ],
       [ 0.20141457, -0.374155  ,  0.43524618,  0.39880381],
       [-1.66677857, -0.14271892, -1.36189934, -1.28719604],
       [-0.14887164, -0.60559109,  0.21060299,  0.13941922],
       [-0.14887164, -1.06846325, -0.12636179, -0.24965767],
       [ 0.31817664, -0.60559109,  0.15444219,  0.13941922],
       [ 0.66846286, -0.83702717,  0.88453256,  0.91757299],
       [ 0.0846525 , -0.14271892,  0.77221097,  0.7878807 ],
       [-0.49915786, -0.14271892,  0.43524618,  0.39880381],
       [-0.26563371, -0.60559109,  0.65988937,  1.04726529],
       [ 2.18636979,  1.

In [5]:
X_test

array([[-0.14887164, -0.374155  ,  0.26676379,  0.13941922],
       [ 0.31817664, -0.60559109,  0.54756778,  0.00972692],
       [ 0.31817664, -1.06846325,  1.05301496,  0.26911151],
       [-1.5500165 , -1.7627715 , -1.36189934, -1.15750374],
       [ 0.0846525 ,  0.32015325,  0.60372857,  0.7878807 ],
       [ 0.78522493, -0.14271892,  0.99685416,  0.7878807 ],
       [-0.84944407,  1.70876975, -1.24957775, -1.15750374],
       [ 0.20141457, -0.14271892,  0.60372857,  0.7878807 ],
       [-0.38239578,  2.63451409, -1.30573855, -1.28719604],
       [-0.38239578, -1.29989934,  0.15444219,  0.13941922],
       [ 0.66846286,  0.08871717,  0.99685416,  0.7878807 ],
       [-0.38239578,  1.0144615 , -1.36189934, -1.28719604],
       [-0.49915786,  0.78302542, -1.13725615, -1.28719604],
       [ 0.43493872, -0.60559109,  0.60372857,  0.7878807 ],
       [ 0.55170079, -1.7627715 ,  0.37908538,  0.13941922],
       [ 0.55170079,  0.55158933,  0.54756778,  0.52849611],
       [-1.19973028,  0.

OVR

In [10]:
# class를 구분하기 위한 머신 미리 만들기
svm1 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm2 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm3 = SVC(kernel ='rbf', C = 5, gamma = 5)

In [6]:
#원 핫 인코딩 해주기
y_train = pd.get_dummies(y_train)

In [7]:
y_train

setosa  versicolor  virginica
110       0           0          1
69        0           1          0
148       0           0          1
39        1           0          0
53        0           1          0
..      ...         ...        ...
64        0           1          0
91        0           1          0
81        0           1          0
51        0           1          0
0         1           0          0

[120 rows x 3 columns]

In [12]:
svm1.fit(X_train,y_train.iloc[:,0]) # 0 or not 구분해주는 머신
svm2.fit(X_train,y_train.iloc[:,1]) # 1 or not 구분해주는 머신
svm3.fit(X_train,y_train.iloc[:,2]) # 2 or not 구분해주는 머신
print(svm1.predict(X_test))


[0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0]


In [14]:
# 부호가 모든 같은 경우는 모두 동점인 경우가 생길 것
for i in range(len(X_test)):
    # ~. decision_function을 이용해서 동점인 index 출력하기
    if (np.sign(svm1.decision_function(X_test)[i]) == np.sign(svm2.decision_function(X_test)[i])) and (np.sign(svm2.decision_function(X_test)[i]) == np.sign(svm3.decision_function(X_test)[i])):
        print(f"동점 index[{i}].") #동점인 index 출력하기

동점 index[3].
동점 index[17].
동점 index[18].


In [20]:
def ovr_svm(models, data, labels):#Decision_function을 활용한 ovr
    distance = None #Decision_function을 담기위한배열
    
    for model in models: # svm1,svm2,svm3 모델
        if distance is None: #모델이 비었으면
            distance = model.decision_function(data) # data크기만큼 배열 생성해주기
            #print(distance)
        else:
            distance = np.vstack((distance, model.decision_function(data))) # 모델이 비어있지 않으면 배열을 위에서 아래로 붙이기
            #print(distance)
            
    distance = distance.T #전치하기: data길이x모델 수 의 형태로 바꾸기 위함
    
    result = [] # 결과값 저장할 list 생성
    
    for pred in distance:
        result.append(labels[pred.argmax()]) # 각 예측들에 대해서 가장 큰 값을 가지는 결과값(argmax) 에 해당하는 꽃을 저장

    
    print(f"prediction : \n {result}")
    return result

models = [svm1, svm2, svm3]
labels = ["setosa", "versicolor", "virginica"]

prediction = ovr_svm(models, X_test, labels) #예측진행

accuracy_score(y_test,prediction) #스코어 출력

prediction : 
 ['versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica', 'virginica', 'setosa', 'virginica', 'setosa', 'versicolor', 'virginica', 'setosa', 'setosa', 'virginica', 'versicolor', 'versicolor', 'setosa', 'versicolor', 'virginica', 'virginica', 'setosa', 'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa', 'virginica', 'virginica', 'versicolor']


0.8666666666666667